{
 "title": "Minecraft Player Comparison",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Player status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_health_total", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Food level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_food_level_total", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Current level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_current_level_total", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_score_total", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "XP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mc_xp_total", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Fighting stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damage dealt",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_damage_dealt_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Damage taken",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_damage_taken_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Kills",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_kills_absolute_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Deaths",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_deaths_total", "legendFormat": "{{player}}" }
     ]
    }
   ]
  },
  {
   "title": "TIme Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time played",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_minutes_played_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Average playing session duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mc_minutes_played_total/mc_left_game_total",
       "legendFormat": "{{player}}"
      }
     ]
    },
    {
     "title": "Times player left the game",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_left_game_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Time since death",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_time_since_death_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Time since last ingame sleep",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_time_since_rest_total", "legendFormat": "{{player}}" }
     ]
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Crafting table used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_craftingtable_used_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Chests opened",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_chests_opened_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Furnace used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mc_interaction_with_furnace_total",
       "legendFormat": "{{player}}"
      }
     ]
    },
    {
     "title": "Beds used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_sleeped_bed_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Animals bred",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_animals_bred_total", "legendFormat": "{{player}}" }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items crafted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_items_crafted_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Items used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_items_used_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Picked up items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_pickedup_items_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Dropped items",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_dropped_items_total", "legendFormat": "{{player}}" }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jumps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_jumps_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Time sneaked",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_time_sneaked_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Advancements",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_advancements_total", "legendFormat": "{{player}}" }
     ]
    },
    {
     "title": "Drops",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "mc_drops_total", "legendFormat": "{{player}}" }
     ]
    }
   ]
  }
 ]
}